[package]
name = "refprop-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2.164"
thiserror = "2.0.3"

[build-dependencies]
bindgen = "0.70.1"
cmake = "0.1.51"
git2 = "0.19.0"
